tests:
  dash:
    params:
      name: dash
      mpd: /www/20min/20min.mpd
      duration: 60
      eachSegDuration: 5
      play_strategy: netflix
  plt:
    params:
      name: plt
  basic:
    params:
      name: basic
      duration: 15
      n_tcp_streams: 1
      report_interval: 0.5
  fairness:
    params:
      name: fairness
      duration: 15
      n_tcp_streams: 2
      report_interval: 0.5
  init:
    params:
      name: init
mn:
  bw: 10
  loss: 7
  delay: 25
