tests:
  dash:
    params:
      name: dash
      mpd: /www/video/20mins/20mins.mpd
      duration: 100
      eachSegDuration: 5
      play_strategy: netflix
  plt:
    params:
      name: plt
  basic:
    params:
      name: basic
      duration: 15
      n_tcp_streams: 1
      report_interval: 0.5
  fairness:
    params:
      name: fairness
      n_tcp_streams: 1
  init:
    params:
      name: init
mn:
  bw: 100
  loss: 0
  delay: 2.5
