tests:
  video_stream:
    params:
      name: video_stream
      mpd: /www/video/20mins/20mins.mpd
      duration: 100
      eachSegDuration: 5
      play_strategy: netflix
  plt:
    params:
      name: plt
  throughput:
    params:
      name: throughput
  fairness:
    params:
      name: fairness
      n_tcp_streams: 1
  quic_std:
    params:
      name: quic_std
mn:
  bw: 10
  loss: 1
  delay: 10
